### ISSUE TITLE
Special-cased support for ML.NET

### ISSUE THREAD

**Issue by abock** [Microsoft/workbooks#303]
While we still need to figure out a better general solution for NuGet packages that depend on native libraries (since there is no standard/conventional way to know what to load, see #204), we should special-case [ML.NET](https://github.com/dotnet/machinelearning) support just as we do for a number of other interesting NuGet packages that natively integrate with the target platform.

See https://github.com/dotnet/machinelearning/issues/157 for more bug details. We should continue any discussion here.

We are gearing up for a minor bug fix release against the 1.4 series and a fix for ML.NET support should be trivial enough to include.

Thanks @cosmincatalin for filing the original issue.

**Comment by sandyarmstrong** [comment]
One thing to note: ML.NET does not have support for 32-bit platforms, and our .NET Core agent is still 32-bit on Windows. I don't see that changing in 1.4.x.

So this special-cased support will only be for:

* Console (.NET Framework) on 64-bit Windows
* WPF on 64-bit Windows
* Console (Mono) on Mac
* .NET Core on Mac
* Xamarin.Mac

**Comment by migueldeicaza** [comment]
Why can we not do .NET Core agent as 64 on Windows?

**Comment by abock** [comment]
I think we're going to have to eat the size overhead again. I would much rather see ML.NET support on .NET Core 64 bit Windows.

**Comment by sandyarmstrong** [comment]
@abock fine by me. Do you want it for 1.4.1?

**Comment by abock** [comment]
Yes.

**Comment by sandyarmstrong** [comment]
What we ended up doing is adding a 64-bit .NET Core agent app on Windows, and the client picks the correct app depending on the OS.

32-bit Windows still won't be able to use ML.NET, but 64-bit Windows will, with .NET Core or .NET Framework (or the WPF agent app).

On Mac, ML.NET will only be usable on Mono for Workbooks 1.4.1. @bojanrajkovic started work on a way to support native libraries for .NET Core on Mac, but it won't make it for 1.4.1. .NET Core workbooks on Mac continue to have no native library support.

I'm closing this even though the fix is only merged in the 1.4 branch, and not in master.
