### ISSUE TITLE
Auto-generation of "Index" File

### ISSUE THREAD

**Issue by anegg0** [Microsoft/workbooks#518]
### Steps to Reproduce

1. Create a new workbook and embed a picture from a folder in local disk
2. Open the workbook

### Expected Behavior
Created workbook remains a single file.
### Actual Behavior
A folder is automatically generated. That folder contains various items, the embedded pictures, along with the initial workbook, now renamed "index.workbook"
#### Xamarin Workbooks
| Detail | Value |
| :- | :- |
| Version | 1.5.0 |
| Git Branch | 1.5-release |
| Git Hash | 11f83dc |
| VSTS Definition | Workbooks & Inspector (Win) |

#### System Info
| Component | Value |
| :- | :- |
| Windows | Microsoft Windows NT 10.0.17134.0 (64-bit) |
| CPU Cores | 2 |
| Physical Memory | 4 GB |

#### System-Installed Software
| Component | Version |
| :- | :- |
| Xamarin Simulator | 1010300016 |

#### VisualStudio.15.Preview Components
| Component | Version |
| :- | :- |
| Visual Studio Community 2017 | 15.9.4-pre.1.0+28307.222 |
| Xamarin iOS | 12.2.1-12 |
| Xamarin Android | 9.1.4-2 |

### Log File

[Xamarin Workbooks 2019-01-17.log](https://github.com/Microsoft/workbooks/files/2768713/Xamarin.Workbooks.2019-01-17.log)

**Comment by sandyarmstrong** [comment]
This is intended behavior, though I agree it can be confusing. This is meant to ensure that if you redistribute your workbook, your resources are included.

If I remember correctly, you can prevent this from happening by using absolute paths to resources instead of relative paths.

https://docs.microsoft.com/en-us/xamarin/tools/workbooks/workbook#workbooks-files-types

**Comment by anegg0** [comment]
noted your proposed workaround, @sandyarmstrong , I tried, it works for me, thanks.
